### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mojoaxel** [thomaswelborn/mvc-framework#1]
This is missing license information.

If you could release this as "[public domain](http://unlicense.org/)" that would be just amazing!

**Comment by thomaswelborn** [comment]
Whoops!

**Comment by mojoaxel** [comment]
I just saw the [package.json](https://github.com/thomaswelborn/mvc-framework/blob/master/package.json#L17) mentions the ISC license.

Please consider [adding a LICENSE file so that GitHub can recognice the license](https://help.github.com/articles/licensing-a-repository/).
